name: my_new_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.16
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cpuonly
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyter_client
  - ipykernel
  - ipython
  - jinja2
  - requests
  - tqdm
  - setuptools
  - pip
  - pip:
      - albumentations==2.0.7
      - altair==5.5.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - click==8.2.0
      - gitpython==3.1.44
      - jsonschema==4.23.0
      - narwhals==1.40.0
      - opencv-python-headless==4.11.0.86
      - pillow==11.2.1
      - protobuf==6.31.0
      - pyarrow==20.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - referencing==0.36.2
      - rpds-py==0.25.0
      - smmap==5.0.2
      - streamlit==1.45.1
      - tenacity==9.1.2
      - watchdog==6.0.0
      - numpy==1.26.4
